import { Poppins } from 'next/font/google';
import "./globals.css";
import "./Components/Navbar/Navbar"
import Navbar from "./Components/Navbar/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500'], // Add different weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
